In [1]:
import pandas as pd

## Texas

In [2]:
# https://www.ethics.state.tx.us/search/cf/ 
# --> on the left hand side menu, select "Database of Campaign Finance Reports"
# --> "CSV Record Layouts" has two links to the data dictionaries
# --> "Campaign Finance CSV Database (As of ...)" will download all the contrib datasets (ours is as of 7/17/2023)

In [3]:
#one example
contrib03 = pd.read_csv("raw_data/contribs_03.csv", low_memory = False)
#column "filerName" tells us corp that donated
#NO AMOUNTS

In [4]:
contrib03.head()

,recordType,formTypeCd,schedFormTypeCd,reportInfoIdent,receivedDt,infoOnlyFlag,filerIdent,filerTypeCd,filerName,contributionInfoId,...,contributorStreetRegion,contributorEmployer,contributorOccupation,contributorJobTitle,contributorPacFein,contributorOosPacFlag,contributorLawFirmName,contributorSpouseLawFirmName,contributorParent1LawFirmName,contributorParent2LawFirmName
0,RCPT,MPAC,A1,350813,20071005,N,15540,MPAC,Valero Energy Corporation Political Action Com...,101000001,...,NaN,Valero Services Inc.,Manager Maintenance - RT,NaN,NaN,N,NaN,NaN,NaN,NaN
1,RCPT,MPAC,A1,607757,20140305,N,15540,MPAC,Valero Energy Corporation Political Action Com...,101000002,...,NaN,Valero Services Inc.,Accounting Specialist,NaN,0.00,N,NaN,NaN,NaN,NaN
2,RCPT,MPAC,A1,350813,20071005,N,15540,MPAC,Valero Energy Corporation Political Action Com...,101000003,...,NaN,Valero Refining - Texas L.P.,Superintendent Maintenanc,NaN,NaN,N,NaN,NaN,NaN,NaN
3,RCPT,MPAC,A1,607757,20140305,N,15540,MPAC,Valero Energy Corporation Political Action Com...,101000004,...,NaN,Valero Services Inc.,Director Asphalt Marketin,NaN,0.00,N,NaN,NaN,NaN,NaN
4,RCPT,MPAC,A1,353861,20071205,N,15540,MPAC,Valero Energy Corporation Political Action Com...,101000005,...,NaN,Valero Marketing and Supply Co.,Conversion Specialist,NaN,NaN,N,NaN,NaN,NaN,NaN

In [12]:
def get_date(x):
    x = str(x)
    year = x[:4]
    month = x[4:6]
    day = x[6:]
    return year + "-" + month + "-" + day

In [15]:
contrib03["date"] = contrib03['receivedDt'].apply(get_date)
contrib03["date"] = pd.to_datetime(contrib03["date"])

In [25]:
contrib03['contributorEmployer'].unique()

array(['Valero Services Inc.', 'Valero Refining - Texas L.P.',
       'Valero Marketing and Supply Co.', ...,
       'GENON NORTHEAST MGMT COMP', 'GENON FLORIDA LP',
       'GENON POWER OP SVCS MWEST'], dtype=object)

In [20]:
#https://www.ethics.state.tx.us/search/cf/cANDelists2021-2016.php#2020
tx_pacs = pd.read_excel("raw_data/2020_PACs_By_Total_Contribs.xlsx")
# GIVES TOTAL AMOUNTS BUT NOT BY CANDIDATE, etc.

/opt/tljh/user/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [21]:
tx_pacs["Filer Name"] = tx_pacs["Filer Name"].str.upper()

In [22]:
tx_pacs.head()

,#,Contributions Received,Political Expenditures,Filer Type,Filer Name,Filer ID,City,State
0,1,"$20,449,698.10","$19,627,607.37",GPAC,ACTBLUE TEXAS,59791,Somerville,MA
1,2,"$17,388,022.78","$6,748,000.00",GPAC,FORWARD MAJORITY ACTION,84594,Washington,DC
2,3,"$11,857,225.00","$17,011,825.68",GPAC,TEXANS FOR LAWSUIT REFORM PAC,28135,Austin,TX
3,4,"$10,749,022.88","$11,301,040.44",GPAC,FORWARD MAJORITY ACTION TEXAS,84123,Washington,DC
4,5,"$10,096,825.00","$10,098,069.84",GPAC,REPUBLICAN STATE LEADERSHIP COMMITTEE PAC AND ...,66771,Washington,DC

## Minnesota

In [ ]:
#Minnesota campaign finance
# https://cfb.mn.gov/reports-and-data/self-help/data-downloads/campaign-finance/

In [5]:
#finance data from 2015-present
mn_money = pd.read_csv("raw_data/Minnesota Campaign Finance.csv")

mn_money["Contrib Employer name"] = mn_money["Contrib Employer name"].str.upper()
#Has amounts and contributors in "Contrib Employer Name" and years

/tmp/ipykernel_2640286/8930675.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  mn_money = pd.read_csv("raw_data/Minnesota Campaign Finance.csv")

In [6]:
mn_money.head()

,Recipient reg num,Recipient,Recipient type,Recipient subtype,Amount,Receipt date,Year,Contributor,Contrib Reg Num,Contrib type,Receipt type,In kind?,In-kind descr,Contrib zip,Contrib Employer name
0,17752,"Folken, Bruce House Committee",PCC,NaN,363.96,07/11/2015,2015,"Folken, Debra",NaN,Individual,Contribution,No,NaN,55124,SCHOOL DISTRICT 196
1,17439,"McKendry, Laurie Senate Committee",PCC,NaN,100.00,04/18/2015,2015,"Burns, Sally M",NaN,Individual,Contribution,No,NaN,55347,SELF EMPLOYED RETIRED
2,17375,"Petersen, Branden Senate Committee",PCC,NaN,150.00,01/27/2015,2015,"Appleby, Jennifer",NaN,Individual,Contribution,No,NaN,55433,NaN
3,17931,"Hassan, Mohamoud Senate Committee",PCC,NaN,300.00,04/11/2016,2016,"Ahmed, Abdinasir",NaN,Individual,Contribution,No,NaN,55404,NaN
4,17931,"Hassan, Mohamoud Senate Committee",PCC,NaN,250.00,04/15/2016,2016,"Hassan, Mohamud",NaN,Individual,Contribution,No,NaN,55404,MIDWEST HOME HEALTH CARE

## Michigan

In [ ]:
# https://www.michigan.gov/sos/elections/disclosure/cfr/committee-search/intro/welcome-to-the-michigan-campaign-finance-searchable-database
# --> click on Contributions Analysis
# --> select "Download ALL contributions..."
# --> takes you to this page https://miboecfr.nictusa.com/cfr/dumpall/cfrdetail/
# records from 1998- 2023, each contribution file/zip have multiple parts

In [101]:
file_list = []
with open("raw_data/2022_mi_cfr_contributions_00.txt", 'rb') as fp:
    for line in fp:
        file_list.append([line])

In [104]:
file_list[1]

[b'517551\t0\t8210\t0\t2022\tJANUARY QUARTERLY CS\tBUTZEL LONG POLITICAL ACTION COMMITTEE\tBUTZEL LONG PAC\t500841\tIND\t\t\tDIRECT                        \tFREDERICK           \tBERG                                \t1033 YORKSHIRE\tGROSSE POINTE PARK  \tMI\t48230-0000\tATTORNEY\tBUTZEL LONG\t11/04/2021\t100.00\t550.00\t\t\n']

In [115]:
# Input
data_file = "raw_data/2022_mi_cfr_contributions_00.txt"

# Delimiter
data_file_delimiter = '\t'

# The max column count a line in the file could have
largest_column_count = 0

# Loop the data lines
with open(data_file, 'r', encoding="utf8", errors='ignore') as temp_f:
    # Read the lines
    lines = temp_f.readlines()

    for l in lines:
        # Count the column count for the current line
        column_count = len(l.split("\t")) + 1
        
        # Set the new most column count
        largest_column_count = column_count if largest_column_count < column_count else largest_column_count

# Generate column names (will be 0, 1, 2, ..., largest_column_count - 1)
column_names = [i for i in range(0, largest_column_count)]

# Read csv
df = pd.read_csv(data_file, header=None, delimiter=data_file_delimiter, names=column_names)
# print(df)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 44266: invalid start byte

In [103]:
#one example

#mich = pd.read_fwf("raw_data/2022_mi_cfr_contributions_00.txt")
mich = pd.read_csv("raw_data/2022_mi_cfr_contributions_00.txt", sep = "\t")
# with open("raw_data/2022_mi_cfr_contributions_00.txt", 'rb') as f:
#     mich = f.read()

ParserError: Error tokenizing data. C error: Expected 27 fields in line 358, saw 28

In [ ]:
## CAN'T FIGURE OUT HOW TO READ IN THIS ZIP FILE

## Pennsylvania

In [ ]:
# https://www.dos.pa.gov/VotingElections/CandidatesCommittees/CampaignFinance/Resources/Pages/FullCampaignFinanceExport.aspx?&&p_SortBehavior=0&p_FileLeafRef=2023%2ezip&&PageFirstRow=1&&View={3CE6D3FC-6EF2-4804-BC1C-DB186903A0E1}
# lots of years, each with their own zip file; contrib file is the one with contribution info inside the folders

In [15]:
contrib_2022_columns = ["REPORTID", "FILERID", "EYEAR", "TIMESTAMP", "CYCLE",
                     "SECTION","CONTRIBUTOR", "ADDRESS1","ADDRESS2", "CITY",
                     "STATE", "ZIPCODE", "OCCUPATION", "ENAME", "EADDRESS1",
                     "EADDRESS2", "ECITY", "ESTATE", "EZIPCODE", "CONTDATE1", 
                     "CONTAMT1","CONTDATE2", "CONTAMT2", "CONTDATE3", "CONTAMT3", 
                     "CONTDESC"]

contrib_columns = ["FILERID", "TIMESTAMP", "CYCLE",
                     "SECTION","CONTRIBUTOR", "ADDRESS1","ADDRESS2", "CITY",
                     "STATE", "ZIPCODE", "OCCUPATION", "ENAME", "EADDRESS1",
                     "EADDRESS2", "ECITY", "ESTATE", "EZIPCODE", "CONTDATE1", 
                     "CONTAMT1","CONTDATE2", "CONTAMT2", "CONTDATE3", "CONTAMT3", 
                     "CONTDESC"]

filer_2022_columns = ["REPORTID", "FILERID", "EYEAR", "TIMESTAMP", "CYCLE",
                     "AMMEND", "TERMINATE", "FILERTYPE", "FILERNAME", "OFFICE",
                     "DISTRICT", "PARTY", "ADDRESS1", "ADDRESS2", "CITY",
                     "STATE", "ZIPCODE", "COUNTY", "PHONE", "BEGINNING", 
                     "MONETARY", "INKIND"]

filer_columns = ["FILERID", "EYEAR", "CYCLE",
                     "AMMEND", "TERMINATE", "FILERTYPE", "FILERNAME", "OFFICE",
                     "DISTRICT", "PARTY", "ADDRESS1", "ADDRESS2", "CITY",
                     "STATE", "ZIPCODE", "COUNTY", "PHONE", "BEGINNING", 
                     "MONETARY", "INKIND"]

In [14]:
penn_2020 = pd.read_csv("contrib_2020.txt", header = None, engine = "python", encoding_errors = 'ignore', on_bad_lines="skip")
penn_2020.columns = contrib_columns

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,8100264,2020,2,IB,Kate E Cianchetta,145 W 11th Ave,Apt 1,Conshohocken,PA,194281417,...,NaN,NaN,NaN,20200416.0,10.0,0,0,0,0,NaN
1,8100264,2020,2,IB,Kate E Cianchetta,145 W 11th Ave,Apt 1,Conshohocken,PA,194281417,...,NaN,NaN,NaN,20200514.0,10.0,0,0,0,0,NaN
2,8100264,2020,2,IB,Walter Cioccia,15 Christopher Dr,NaN,Long Valley,NJ,078533006,...,NaN,NaN,NaN,20200206.0,10.0,0,0,0,0,NaN
3,8100264,2020,2,IB,Walter Cioccia,15 Christopher Dr,NaN,Long Valley,NJ,078533006,...,NaN,NaN,NaN,20200305.0,10.0,0,0,0,0,NaN
4,8100264,2020,2,IB,Walter Cioccia,15 Christopher Dr,NaN,Long Valley,NJ,078533006,...,NaN,NaN,NaN,20200319.0,10.0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241785,9900260,2020,5,IB,Angela Marie Culler,100 Bayer Rd,NaN,Pittsburgh,PA,152059707,...,NaN,NaN,NaN,20200828.0,30.0,0,0,0,0,NaN
1241786,9900260,2020,5,IB,Angela Marie Culler,100 Bayer Rd,NaN,Pittsburgh,PA,152059707,...,NaN,NaN,NaN,20201009.0,30.0,0,0,0,0,NaN
1241787,9900260,2020,5,IB,Matthew Culler,100 Bayer Rd,NaN,Pittsburgh,PA,152059707,...,NaN,NaN,NaN,20200717.0,10.0,0,0,0,0,NaN
1241788,9900260,2020,5,IB,Matthew Culler,100 Bayer Rd,NaN,Pittsburgh,PA,152059707,...,NaN,NaN,NaN,20200731.0,10.0,0,0,0,0,NaN
1241789,9900260,2020,5,IB,Matthew Culler,100 Bayer Rd,NaN,Pittsburgh,PA,152059707,...,NaN,NaN,NaN,20200828.0,10.0,0,0,0,0,NaN

In [6]:
penn_2022 = pd.read_csv("contrib_2022.txt", header = None, engine = "python", encoding_errors = 'ignore', on_bad_lines="skip")
pen_2022.columns = contrib_2022_columns

In [23]:
penn_2022.head()

,REPORTID,FILERID,EYEAR,TIMESTAMP,CYCLE,SECTION,CONTRIBUTOR,ADDRESS1,ADDRESS2,CITY,...,ECITY,ESTATE,EZIPCODE,CONTDATE1,CONTAMT1,CONTDATE2,CONTAMT2,CONTDATE3,CONTAMT3,CONTDESC
0,365777,7900009,2022,2022-03-28,1,IC,Ben Shaevitz,141 Porter Road,NaN,Harrisville,...,NaN,NaN,NaN,20220228.0,260.0,0,0,0,0,NaN
1,365777,7900009,2022,2022-03-28,1,IC,T Storm Heter,512 Fulmer Ave,NaN,Stroudsburg,...,NaN,NaN,NaN,20220228.0,260.0,0,0,0,0,NaN
2,373735,7900009,2022,2022-09-19,4,IC,Ben Shaevitz,141 Porter Road,NaN,Harrisville,...,NaN,NaN,NaN,20220829.0,312.0,0,0,0,0,NaN
3,370869,7900009,2022,2022-06-06,3,IC,James Jones,26 Wakefield Dr,NaN,Newark,...,NaN,NaN,NaN,20220527.0,300.0,0,0,0,0,NaN
4,373735,7900009,2022,2022-09-19,4,IC,Calvin Walker,27 Hagerty Lane,NaN,Cranbury,...,NaN,NaN,NaN,20220610.0,300.0,0,0,0,0,NaN

In [ ]:
#Process for downloading files for each year
contrib_df = pd.read_csv("contrib_YYYY.txt", header = None, engine = "python", encoding_errors = 'ignore', on_bad_lines="skip")
filer_df = pd.read_csv("filer_YYYY.txt", header = None, engine = "python", encoding_errors = 'ignore', on_bad_lines="skip")

contrib_df.columns = contrib_columns
contrib_df.to_csv("pa_contrib_YYYY.csv")

filer_df.columns = filer_columns
filer_df.to_csv("pa_filer_YYYY.csv")

## North Carolina

In [ ]:
# https://www.ncsbe.gov/campaign-finance/search-campaign-funding-and-spending-reports-and-penalties

# still looking for how to download

## Arizona

In [ ]:
# https://azsos.gov/elections/campaign-finance-reporting

# still looking for how to download

## Virginia

In [ ]:
# https://www.elections.virginia.gov/candidatepac-info/reporting/
# --> click on 
# --> takes you to the download page https://apps.elections.virginia.gov/SBE_CSV/CF/

# there are multiple files for each year

In [65]:
# one example
virginia = pd.read_csv("ScheduleE.csv")
# ... don't know if this is what I am looking for

In [68]:
virginia["LenderLastOrCompanyName"].unique()

array(['Economy Printing, Inc', 'Whitehurst', 'David', 'Coplan', 'Miller',
       'Mauch', 'Price', 'Jarmon', 'Jones', 'Gerdes', 'Kelsey', 'Newins',
       'Pollard', 'Montgomery', 'Hartley', 'Nevill', 'MacDonald',
       'Hoyler', 'Kowalewitch', 'Bouchard', 'Bredemeyer', 'Hall', 'Meyer',
       'Hatter', 'Nagel', 'Best', 'Silverman', 'Campbell', 'Sullivan',
       'Orenic', 'Jagadev', 'Holliday', 'de Triquet', 'Brian', 'Economy',
       'BATTLE', 'Mooney', 'Copeland', 'McPherson', 'Bowman', 'Regan',
       'Cave', 'Jenkins', 'Taylor', 'Policy Planning & Evaluation, Inc.',
       'Auguste', 'Mitchell', 'Gray', 'Foley', 'Smith', 'Pifer',
       'Westbrook', 'Paige', 'Riddick', 'ELLIS', 'Fleming', 'Dean',
       'Brown-Yearling', 'Maxwell', 'Iqbal', 'Wilson', 'Snyder',
       'Lipscomb'], dtype=object)

In [76]:
pd.read_csv("ff_industry.csv")

                                        Name
0                            KOCH INDUSTRIES
1                               CHEVRON CORP
2                         WILLIAMS COMPANIES
3                                EXXON MOBIL
4                         MARATHON PETROLEUM
...                                      ...
4579                              CUMBERLAND
4580          PRACTICAL ENERGY SOLUTIONS LLC
4581                     YOUNG REFINING CORP
4582  CONSOLIDATED GLASS AND MIRROR CORPORAT
4583                      GP BIG ISLAND, LLC

[4584 rows x 1 columns]

In [ ]:
#standardize case + other cleaning
#record linkage - fuzzy matching
# jaro-winkler
# levensteiner
# federal databases fein number


#use edgar api on SEC website
#filter by relevant SIC codes and map .... still need fuzzy matching 



## Arizona - I need to find the files
## North Carolina - I need to find the files
## virginia missing information